#!/bin/bash

# https://unix.stackexchange.com/questions/26676/how-to-check-if-a-shell-is-login-interactive-batch
is_interactive_shell() {
    [[ $- == *i* ]]
}

if is_interactive_shell; then
    # C-w で単語削除を行う際に、スペースだけでなく / も単語の区切りとみなす
    stty werase undef
    bind '"\C-w": unix-filename-rubout'
fi

mkcd() {
    mkdir "$1" && cd "$_"
}

# for gpg
if command -v gpgconf > /dev/null; then
    export GPG_TTY=$(tty)
    gpgconf --launch gpg-agent
    #gpgconf --launch dirmngr
fi

# for ssh-agent
if [[ -n "$XDG_RUNTIME_DIR" ]]; then
    export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
fi

eval "$(starship init bash)"
eval "$(fzf --bash)"
eval "$(zoxide init bash)"

if [[ -f ~/.cargo/env ]]; then
    . ~/.cargo/env
fi

if [[ -f ~/.ghcup/env ]]; then
    . ~/.ghcup/env
fi

if [[ -f ~/.elan/env ]]; then
    . ~/.elan/env
fi

if [[ -d "$HOME/.local/bin" ]]; then
    export PATH="$HOME/.local/bin:$PATH"
fi
