#!/bin/bash

# https://unix.stackexchange.com/questions/26676/how-to-check-if-a-shell-is-login-interactive-batch
is_interactive_shell() {
    [[ $- == *i* ]]
}

if is_interactive_shell; then
    # C-w で単語削除を行う際に、スペースだけでなく / も単語の区切りとみなす
    stty werase undef
    bind '"\C-w": unix-filename-rubout'
fi

# for gpg
if command -v gpgconf > /dev/null; then
    export GPG_TTY=$(tty)
    gpgconf --launch gpg-agent
    gpgconf --launch dirmngr
fi

eval "$(starship init bash)"
eval "$(fzf --bash)"
eval "$(zoxide init bash)"

if [[ -f ~/.cargo/env ]]; then
    . ~/.cargo/env
fi

if [[ -f /home/nojima/.ghcup/env ]]; then
    . /home/nojima/.ghcup/env
fi
